### ISSUE TITLE
Create a Profile Page

### ISSUE THREAD

**Issue by CheshtaK** [CheshtaK/bookface#5]
**Is your feature request related to a problem? Please describe.**
Design and create a profile page for the app.

**Describe the solution you'd like**
Include all the relevant fields such as Name, Bio, DOB, profile picture, etc.

**Additional context**
Attach a screenshot of the new page or a working gif while creating a pull request.  Follow the [contributing guidelines](https://github.com/CheshtaK/bookface/blob/master/.github/CONTRIBUTING.md).

**Comment by ishandeveloper** [comment]
I can work on this, @CheshtaK .

**Comment by CheshtaK** [comment]
Assigned you @ishandeveloper! Do you have a design in mind? Let's discuss it here and then you can go ahead and implement it.

**Comment by ishandeveloper** [comment]
Sure, @CheshtaK .
Below are screenshots from one of my own projects. I am initially thinking of something quite similar to this : 
<img src="https://user-images.githubusercontent.com/54989142/86512815-f104a380-be22-11ea-9754-056608cc87b1.jpg" height="450em" /><img src="https://user-images.githubusercontent.com/54989142/86512861-3923c600-be23-11ea-87ae-d301eb6b9bde.jpg" height="450em">
The basic layout would be the same, instead of calling the posts 'Gits' we would call them **'Reads'**
We will provide two views, a grid view and a list view, similar to that on Instagram. 
<img src="https://user-images.githubusercontent.com/54989142/86513046-a97f1700-be24-11ea-99a6-6cf6966f7c23.jpg" height="400em"/>
Single Post (*Read*). 
I'm thinking of adding some padding and circular border radius to the post with a custom background color to the post container, as you mentioned before.

**Comment by CheshtaK** [comment]
Yes looks good @ishandeveloper! Implement the list view's post card as a separate widget. We can use it for our Feed page too!

**Comment by ishandeveloper** [comment]
Hey @CheshtaK . Here's what I've created so far.

`Note : The GIF might take some time to load...`
<img src="https://user-images.githubusercontent.com/54989142/86818190-b2c9e700-c0a3-11ea-93b3-439659dfc497.gif" height="450em" />

Let me know your thoughts, if like it, i'll create a PR regarding the same.

**Comment by CheshtaK** [comment]
This is amazing work @ishandeveloper! You can go ahead and open a PR

**Comment by ishandeveloper** [comment]
Just linked a PR, @CheshtaK @himanshusharma89
